before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash
    - export PATH="$HOME/.yarn/bin:$PATH"
language: node_js
node_js:
    - "6"
    - "8"
    - "9"
    - "10"
script:
    - yarn lint
    - yarn test
